[pytest]
testpaths = tests
addopts = --cov --cov-report=term-missing --cov-report=html --html=htmlcov/report.html --self-contained-html

[coverage:run]
source = .
include = core/*
relative_files = true

[coverage:xml]
output = coverage.xml
